version: "3.7"

services:

    iobroker:
        build: ./armv7hf
        image: samosir/iobroker-slave:latest
        env_file: iob-slave.env
        hostname: iobroker_slave
        container_name: iobroker-slave
        restart: always
        network_mode: bridge
        expose:
           - 8081 
           - 8082
        ports:
           - "8081:8081"
           - "8082:8082"
           - "1883:1883"
           - "1886:1886"
        cap_add:
           - NET_ADMIN
        volumes:
           - /opt/iobroker/:/opt/iobroker/
        

